In [1]:
import numpy as np

In [2]:
x=[1,2,3]

In [3]:
type(x)

list

In [ ]:
list()
str()

In [4]:
y=np.array(x)

In [5]:
x

[1, 2, 3]

In [6]:
y

array([1, 2, 3])

In [7]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [8]:
y/2

array([0.5, 1. , 1.5])

In [16]:
x=[2.61,2,3]
y=np.array(x)

In [17]:
x

[2.61, 2, 3]

In [18]:
y

array([2.61, 2.  , 3.  ])

### 🧮 NumPy Data Types, Type Codes, and Ranges

| **Type**                   | **Type Code**  | **Range**                                                                 |
|---------------------------|----------------|---------------------------------------------------------------------------|
| `int8`                    | `i1`           | -128 to 127                                                               |
| `uint8`                   | `u1`           | 0 to 255                                                                  |
| `int16`                   | `i2`           | -32,768 to 32,767                                                         |
| `uint16`                  | `u2`           | 0 to 65,535                                                               |
| `int` or `int32`          | `i4` or `i`    | -2,147,483,648 to 2,147,483,647                                           |
| `uint32`                  | `u4`           | 0 to 4,294,967,295                                                        |
| `int64`                   | `i8`           | -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807                   |
| `uint64`                  | `u8`           | 0 to 18,446,744,073,709,551,615                                           |
| `float16`                 | `f2`           | ±5.96e-8 to ±65504                                                        |
| `float32`                 | `f4` or `f`    | ±1.18e-38 to ±3.4e+38                                                     |
| `float` or `float64`      | `f8` or `d`    | ±2.23e-308 to ±1.8e+308                                                   |
| `float128` (platform dep) | `f16` or `g`   | ±1.18e-4932 to ±1.18e+4932 *(on compatible platforms)*                    |
| `complex64`               | `c8`           | Real and imaginary parts as `float32`                                     |
| `complex` or `complex128`| `c16`          | Real and imaginary parts as `float64`                                     |
| `bool`                    | *None*         | `True` or `False`                                                         |
| `object`                  | `O`            | Python objects                                                            |
| `string_`                 | `S`            | Fixed-length ASCII string                                                 |
| `unicode_`                | `U`            | Fixed-length Unicode string                                               |


In [19]:
x=[[1,2],[4,5]]

In [20]:
x

[[1, 2], [4, 5]]

In [22]:
y=np.array(x)

In [24]:
type(x)

list

In [23]:
y

array([[1, 2],
       [4, 5]])

In [25]:
type(y)

numpy.ndarray

In [26]:
y/2

array([[0.5, 1. ],
       [2. , 2.5]])

In [28]:
x=np.array([1,2,3,4])

In [31]:
y=np.array([[1,2],[2,3]])

In [32]:
y

array([[1, 2],
       [2, 3]])

In [33]:
x

array([1, 2, 3, 4])

In [35]:
np.info(x)

class:  ndarray
shape:  (4,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x25f5622b060
byteorder:  little
byteswap:  False
type: int32


In [36]:
np.info(y)

class:  ndarray
shape:  (2, 2)
strides:  (8, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x25f562284a0
byteorder:  little
byteswap:  False
type: int32


In [39]:
x.dtype,y.dtype

(dtype('int32'), dtype('int32'))

In [40]:
len(x)

4

In [41]:
len(y)

2

In [42]:
x.ndim

1

In [43]:
y.ndim

2

In [44]:
x.itemsize

4

In [45]:
y.itemsize

4

In [46]:
#### data creation functions

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [51]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [77]:
np.random.randint(0,10)

0

In [106]:
np.random.randint(10000,2000000,100)

array([1810654,  314897, 1580402, 1198552, 1304506,  437161,  776218,
        953606, 1373039,  685691, 1566612,  380126,  986678, 1476108,
        823936, 1649985, 1869988, 1203153, 1522983, 1074906, 1315514,
       1923422, 1303826,  687885,  663284,  121673, 1675459,  162918,
       1702982,  996908, 1490680,  685753, 1306142,  360552, 1408104,
        406723,  302026, 1037104,  967499,  876132,  735254,  693012,
         50305,  813290, 1343033,  371952,   26459,  930902, 1925241,
        869372, 1414457, 1067871, 1158423, 1924934,  990653, 1476440,
       1313967, 1293209,  782488, 1820477, 1631304,   49534, 1812841,
       1023369,  999938,  886033, 1565748,  558409,  981759, 1455538,
       1980180, 1054950,   21589,  862432, 1351647,  167736, 1686924,
        290845,   21332,  231207, 1392643, 1033117,  444600,  986474,
        673460, 1168904,   95312, 1840890, 1358073,  781496,  354660,
       1151205, 1369378,   84657, 1788235, 1000541, 1446400,  564160,
       1656284,  197

In [107]:
np.random.rand(10)

array([0.29681931, 0.1027776 , 0.08492874, 0.35391725, 0.03228809,
       0.21815616, 0.36944287, 0.20200874, 0.95239274, 0.66680485])

In [108]:
np.random.randn(10)  ### normal distribution of data

array([ 0.36326531, -0.44111083,  0.36191313, -1.49962138, -1.67681584,
        0.51471287,  0.29098469,  1.27676368,  1.01463911,  1.00200777])

In [112]:
np.random.randn(1000000) .mean()

-0.0003910415994075816

In [110]:
np.random.randn(10) .std()

1.2399956195817052

In [ ]:
#### 

In [113]:
x=np.random.randint(0,10,(2,2))

In [114]:
y=np.random.randint(0,10,(2,2))

In [115]:
x

array([[5, 2],
       [9, 6]])

In [116]:
y

array([[9, 2],
       [5, 0]])

In [117]:
z=10

In [118]:
np.add(x,y)

array([[14,  4],
       [14,  6]])

In [119]:
x=np.random.randint(0,10,(5,5))

In [120]:
x

array([[4, 7, 3, 1, 3],
       [9, 0, 5, 7, 7],
       [3, 3, 7, 3, 0],
       [9, 6, 1, 9, 5],
       [0, 5, 9, 1, 7]])

In [124]:
x[2:5,3:5]

array([[3, 0],
       [9, 5],
       [1, 7]])

In [125]:
x

array([[4, 7, 3, 1, 3],
       [9, 0, 5, 7, 7],
       [3, 3, 7, 3, 0],
       [9, 6, 1, 9, 5],
       [0, 5, 9, 1, 7]])

In [126]:
x[-2:-1,-2:-1]

array([[9]])

In [127]:
x

array([[4, 7, 3, 1, 3],
       [9, 0, 5, 7, 7],
       [3, 3, 7, 3, 0],
       [9, 6, 1, 9, 5],
       [0, 5, 9, 1, 7]])

In [128]:
x[-3:-1,-2:]

array([[3, 0],
       [9, 5]])

In [129]:
### inbuilt functions

In [130]:
x=np.random.randint(0,10,(2,2))

In [131]:
y=np.random.randint(0,10,(2,2))

In [132]:
x

array([[7, 7],
       [0, 4]])

In [133]:
y

array([[3, 7],
       [6, 7]])

In [134]:
np.add(x,y)

array([[10, 14],
       [ 6, 11]])

In [135]:
np.multiply(x,y)

array([[21, 49],
       [ 0, 28]])

In [136]:
np.subtract(x,y)

array([[ 4,  0],
       [-6, -3]])

In [137]:
np.divide(x,y)

array([[2.33333333, 1.        ],
       [0.        , 0.57142857]])

In [138]:
x

array([[7, 7],
       [0, 4]])

In [139]:
y

array([[3, 7],
       [6, 7]])

In [140]:
np.floor_divide(x,y)

array([[2, 1],
       [0, 0]])

In [141]:
np.mod(x,y)

array([[1, 0],
       [0, 4]])

In [142]:
np.power(x,2)

array([[49, 49],
       [ 0, 16]], dtype=int32)

In [149]:
x+10

array([[17, 17],
       [10, 14]])

In [148]:
np.add(x,10)

array([[17, 17],
       [10, 14]])

In [ ]:
####

In [152]:
y=x/3

In [159]:
y=np.array([[1.6,2.3],[3.5,3.9]])

In [160]:
y

array([[1.6, 2.3],
       [3.5, 3.9]])

In [162]:
np.round(y)

array([[2., 2.],
       [4., 4.]])

In [163]:
y=np.array([[-1.6,-2.3-3.5,-3.9]])

In [164]:
y=np.array([[-1.6,-2.3,-3.5,-3.9]])
np.round(y)

array([[-2., -2., -4., -4.]])

In [167]:
y=-1*y
y

array([[1.6, 2.3, 3.5, 3.9]])

In [170]:
np.floor(y)

array([[1., 2., 3., 3.]])

In [171]:
np.ceil(y)

array([[2., 3., 4., 4.]])

In [172]:

np.fix(y)

array([[1., 2., 3., 3.]])

In [173]:
y

array([[1.6, 2.3, 3.5, 3.9]])

In [175]:
y=-1*y

In [176]:
y

array([[-1.6, -2.3, -3.5, -3.9]])

In [177]:
np.fix(y)

array([[-1., -2., -3., -3.]])

In [178]:
np.floor(y)

array([[-2., -3., -4., -4.]])

In [179]:
y

array([[-1.6, -2.3, -3.5, -3.9]])

In [180]:
x=-1*y

In [181]:
x

array([[1.6, 2.3, 3.5, 3.9]])

In [182]:
y

array([[-1.6, -2.3, -3.5, -3.9]])

In [183]:
np.floor(x)

array([[1., 2., 3., 3.]])

In [184]:
np.floor(y)

array([[-2., -3., -4., -4.]])

In [185]:
np.fix(x)

array([[1., 2., 3., 3.]])

In [186]:
np.fix(y)

array([[-1., -2., -3., -3.]])

In [ ]:
### log and exponential

In [187]:
import math
math.e

2.718281828459045

In [188]:
math.pi

3.141592653589793

In [189]:
math.tau

6.283185307179586

In [193]:
np.exp(-2)

0.1353352832366127

In [194]:
np.power(2.718281828459045,-2)

0.1353352832366127

In [197]:
np.exp(2)

7.38905609893065

In [196]:
np.expm1(2)

6.38905609893065

In [198]:
x

array([[1.6, 2.3, 3.5, 3.9]])

In [199]:
np.exp(x)

array([[ 4.95303242,  9.97418245, 33.11545196, 49.40244911]])

In [201]:
np.log(math.e)

1.0

In [202]:
np.log2(2)

1.0

In [200]:
np.log10(10)

1.0

In [203]:
np.log2(16)

4.0

In [204]:
x=2

In [205]:
np.random.randint(0,10,(2,2))

array([[6, 3],
       [7, 0]])

In [206]:
###  statistical functions

In [216]:
data=np.array([10,11,15,21,36,1000])

In [211]:
np.mean(data)

32.166666666666664

In [214]:
(10+11+15+21+36+1000)/6

182.16666666666666

In [217]:
np.median(data)

18.0

In [218]:
[1,1,2,1,1,2,2,2,3]

[1, 1, 2, 1, 1, 2, 3]

AttributeError: module 'numpy' has no attribute 'mode'

In [222]:
data=np.array([-10,0,10,20,30])

In [225]:
(data-data.mean())/len(data)

array([-4., -2.,  0.,  2.,  4.])

In [231]:
data.mean()

10.0

In [226]:
np.std(data)

14.142135623730951

In [230]:
np.sqrt(sum((data-data.mean())**2)/5)

14.142135623730951

In [232]:
np.var(data)

200.0

In [233]:
np.quantile(data,0.25)

0.0

In [236]:
np.quantile(data,0.50)

10.0

In [237]:
data

array([-10,   0,  10,  20,  30])

In [239]:
np.median(data)

10.0

In [240]:
np.quantile(data,0.75)

20.0

In [241]:
np.min(data)

-10

In [242]:
np.max(data)

30

In [ ]:
####

In [244]:
x

2

In [243]:
x
np.sin(x)

0.9092974268256817

In [246]:
np.cos(x),np.tan(x)

(-0.4161468365471424, -2.185039863261519)

In [247]:
np.arcsin(x)

C:\Users\bhara\AppData\Local\Temp\ipykernel_33172\1524129805.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(x)


nan

In [248]:
np.arccos(x)

C:\Users\bhara\AppData\Local\Temp\ipykernel_33172\396561874.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(x)


nan

In [249]:
np.arctan(x)

1.1071487177940904

In [250]:
np.sinh(x),np.cosh(x),np.tanh(x)

(3.6268604078470186, 3.7621956910836314, 0.9640275800758169)

In [252]:
x=np.array([1,2,3,4])

In [253]:
x

array([1, 2, 3, 4])

In [254]:
np.sum(x)

10

In [255]:
np.prod(x)

24

In [257]:
np.cumsum(x)

array([ 1,  3,  6, 10])

In [258]:
np.cumprod(x)

array([ 1,  2,  6, 24])

In [259]:
x=np.random.randint(0,10,(3,3))

In [260]:
x

array([[9, 2, 6],
       [2, 4, 3],
       [3, 3, 4]])

In [261]:
x.sum()

36

In [262]:
x.sum(axis=1)

array([17,  9, 10])

In [263]:
x.sum(axis=0)

array([14,  9, 13])

In [268]:
x=np.random.randint(0,2,(4,4))

In [269]:
x

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 1]])

In [270]:
x.mean()

0.3125

In [271]:
x.mean(axis=1)

array([0.  , 0.25, 0.25, 0.75])

In [272]:
x.mean(axis=0)

array([0.  , 0.75, 0.25, 0.25])

In [273]:
x=np.random.randint(0,10,(4,4))

In [274]:
x

array([[7, 2, 7, 0],
       [2, 7, 3, 7],
       [4, 5, 9, 3],
       [1, 2, 0, 9]])

In [276]:
x.max(axis=0)

array([7, 7, 9, 9])

In [277]:
x.argmax(axis=0)

array([0, 1, 2, 3], dtype=int64)

In [278]:
x.argmin(axis=0)

array([3, 0, 3, 0], dtype=int64)

In [281]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [282]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [284]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [287]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [291]:
data=np.random.randint(0,100,10)

In [292]:
data

array([40, 94, 88, 51, 79, 57,  3, 23, 54, 91])

In [294]:
data[data>50]

array([94, 88, 51, 79, 57, 54, 91])

In [295]:
data

array([40, 94, 88, 51, 79, 57,  3, 23, 54, 91])

In [297]:
data

array([40, 94, 88, 51, 79, 57,  3, 23, 54, 91])

In [298]:
data>50

array([False,  True,  True,  True,  True,  True, False, False,  True,
        True])

In [296]:
np.where(data>50,"high","low")

array(['low', 'high', 'high', 'high', 'high', 'high', 'low', 'low',
       'high', 'high'], dtype='<U4')

In [299]:
data

array([40, 94, 88, 51, 79, 57,  3, 23, 54, 91])

In [301]:
np.any(data>50)

True

In [306]:
np.all(data>0)

True

In [307]:
data>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])